{
 "title": "API Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API Access Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"app\"}",
     "legendFormat": "{{method}} - {{handler}} - {{code}}"
    }
   ]
  },
  {
   "title": "API Errors [5xx]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"app\",code!=\"200\"}",
     "legendFormat": "{{handler}} - {{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[10m])/rate(http_request_duration_seconds_count[10m])",
     "legendFormat": "{{method}} - {{code}} - {{handler}}"
    }
   ]
  }
 ]
}